# Generated by Django 5.1.3 on 2024-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('victim', 'Victim'), ('suspect', 'Suspect'), ('witness', 'Witness'), ('detective', 'Detective')], max_length=10)),
                ('description', models.TextField()),
                ('testimony', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.URLField()),
                ('is_criminal', models.BooleanField(default=False)),
            ],
        ),
    ]
